### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dpryan79** [tomoyukif/GBScleanR#1] opened 2022-11-11 21:45 UTC
While rolling out the Bioconductor 3.16 release on Bioconda, I ran into the following error with GBScleanR:

```
2022-11-11T20:31:16.1715262Z 20:31:16 BIOCONDA INFO (OUT) * installing *source* package ‘GBScleanR’ ...
2022-11-11T20:31:16.1715978Z 20:31:16 BIOCONDA INFO (OUT) ** using staged installation
2022-11-11T20:31:16.1849857Z 20:31:16 BIOCONDA INFO (OUT) ** libs
2022-11-11T20:31:16.1964253Z 20:31:16 BIOCONDA INFO (OUT) $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c++ -std=gnu++11 -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -I'$PREFIX/lib/R/library/RcppParallel/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1667676773505/work=/usr/local/src/conda/r-base-4.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix  -c GBSR_HMM.cpp -o GBSR_HMM.o
2022-11-11T20:31:19.0741641Z 20:31:19 BIOCONDA INFO (OUT) GBSR_HMM.cpp: In function 'std::vector<double> calcGenoprob(const double&, const double&, const double&, const double&, const double&, const double&, const int&)':
2022-11-11T20:31:19.0749378Z 20:31:19 BIOCONDA INFO (OUT) GBSR_HMM.cpp:199:32: error: call of overloaded 'pow10(__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type&)' is ambiguous
2022-11-11T20:31:19.0755353Z 20:31:19 BIOCONDA INFO (OUT)   199 |         prob[g] = pow10(prob[g]);
2022-11-11T20:31:19.0764822Z 20:31:19 BIOCONDA INFO (OUT)       |                                ^
2022-11-11T20:31:19.0765873Z 20:31:19 BIOCONDA INFO (OUT) In file included from /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/features.h:361,
2022-11-11T20:31:19.0769594Z 20:31:19 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_build_env/x86_64-conda-linux-gnu/include/c++/10.4.0/x86_64-conda-linux-gnu/bits/os_defines.h:39,
2022-11-11T20:31:19.0770504Z 20:31:19 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_build_env/x86_64-conda-linux-gnu/include/c++/10.4.0/x86_64-conda-linux-gnu/bits/c++config.h:522,
2022-11-11T20:31:19.0773968Z 20:31:19 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_build_env/x86_64-conda-linux-gnu/include/c++/10.4.0/cstdlib:41,
2022-11-11T20:31:19.0775392Z 20:31:19 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library/RcppParallel/include/RcppParallel/TinyThread.h:4,
2022-11-11T20:31:19.0780688Z 20:31:19 BIOCONDA INFO (OUT)                  from /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library/RcppParallel/include/RcppParallel.h:6,
2022-11-11T20:31:19.0788383Z 20:31:19 BIOCONDA INFO (OUT)                  from GBSR_HMM.cpp:3:
2022-11-11T20:31:19.0789363Z 20:31:19 BIOCONDA INFO (OUT) /opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/bits/mathcalls.h:123:1: note: candidate: 'double pow10(double)'
2022-11-11T20:31:19.0794612Z 20:31:19 BIOCONDA INFO (OUT)   123 | __MATHCALL (pow10,, (_Mdouble_ __x));
2022-11-11T20:31:19.0795038Z 20:31:19 BIOCONDA INFO (OUT)       | ^~~~~~~~~~
2022-11-11T20:31:19.0801026Z 20:31:19 BIOCONDA INFO (OUT) GBSR_HMM.cpp:130:8: note: candidate: 'double pow10(double&)'
2022-11-11T20:31:19.0801504Z 20:31:19 BIOCONDA INFO (OUT)   130 | double pow10(double & d){
2022-11-11T20:31:19.0808861Z 20:31:19 BIOCONDA INFO (OUT)       |        ^~~~~
2022-11-11T20:31:19.5769335Z 20:31:19 BIOCONDA INFO (OUT) make: *** [/opt/conda/conda-bld/bioconductor-gbscleanr_1668198465789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/etc/Makeconf:178: GBSR_HMM.o] Error 1
2022-11-11T20:31:19.5775522Z 20:31:19 BIOCONDA INFO (OUT) ERROR: compilation failed for package ‘GBScleanR’
```

It seems the pow10() call is ambiguous. Please advise.

**Comment by tomoyukif** [comment] 2022-11-14 07:47
I haven't ever seen this compile error with my tested environments and could not find the cause.
Anyway, I made a change in the code and hope it will work.
I pushed the fixed version to the Bioconductor 3.16 repo today.
I guess the latest version will become available within 48 hours.

**Closed** 2022-11-21 08:46 UTC
